[[redirects]]
  from = "/server/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/join/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/create/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/welcome/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/auth"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200
  force = true
